// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyuphgonsvjxffgyrfjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dXBoZ29uc3ZqeGZmZ3lyZmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzUyMTAsImV4cCI6MjA3MzQxMTIxMH0.GIIC8EWPFOpllCMDp2vC9ESUFWckrNUWTuFF3rXJ4pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});